#!/usr/bin/env python3
"""
Port the plugin's material to a Qt Quick shader, and compile it.

The lock screen cannot get its glass the way every other panel does. The plugin
draws glass by hooking renderLayer, which only fires for LAYER surfaces, and a
session-lock surface is not one -- the compositor never offers it to that hook.

But the lock screen is the easy case: it owns the whole scene. The "backdrop"
behind its glass is the wallpaper it drew itself, so there is nothing to
capture. A ShaderEffectSource of that wallpaper is the texture, and the same
maths runs in QML.

This generates rather than copies, so the material stays one file. Edit
plugin/src/brolliglass.frag and re-run; the lock screen follows.

Two mechanical changes and one real one:

  version/layout  Qt's RHI wants #version 440, uniforms in a std140 block, and
                  explicit locations and bindings.
  qt_Opacity      Qt multiplies by it; the plugin has no such concept.
  panelStats      the plugin measures its backdrop with a mipmap-reduce pass
                  and reads the result with texelFetch. There is no such pass
                  here, so the two numbers it produces -- mean luma and mean
                  luma squared -- arrive as a plain uniform the QML side sets.
                  Same maths, same readability behaviour, one less render pass.

Run: python3 splash/port-material.py
Writes splash/glass.frag and splash/glass.frag.qsb, both generated.
"""
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(os.path.dirname(HERE), "plugin", "src", "brolliglass.frag")
OUT_GLSL = os.path.join(HERE, "glass.frag")
OUT_QSB = os.path.join(HERE, "glass.frag.qsb")

# Everything the plugin declares, minus the two that describe a texture we do
# not have. Order matters: this is a std140 block, so it is also the memory
# layout the QML properties line up against.
SCALARS = [
    ("vec2", "panelSize"), ("vec2", "texSize"),
    ("float", "pad"), ("float", "maxCornerRadius"),
    ("float", "aghDepth"), ("float", "aghStrength"), ("float", "aghBlur"),
    ("float", "aghChroma"), ("float", "aghEdge"), ("float", "aghTint"),
    ("float", "aghStretch"),
    ("vec2", "panelStat"),          # replaces the panelStats texture
    ("float", "glassDir"), ("float", "aghSquash"), ("float", "aghPush"),
    ("float", "aghBody"), ("float", "glassOverGlass"),
    ("vec4", "tint"),
    ("float", "power"),
    ("float", "rimHighlightStrength"), ("float", "rimHighlightWidth"),
    ("float", "rimDiagonalReach"),
]


def find_qsb():
    for c in (shutil.which("qsb"), "/usr/lib/qt6/bin/qsb", "/usr/lib/qt/bin/qsb"):
        if c and os.path.exists(c):
            return c
    sys.exit("qsb not found — install qt6-shadertools")


def port(text):
    # Strip the plugin's GLES preamble and every uniform declaration; they are
    # rebuilt below in the order the block needs.
    text = re.sub(r"#version 300 es\n", "", text)
    text = re.sub(r"precision highp (float|sampler2D);\n", "", text)
    text = re.sub(r"^uniform .*\n", "", text, flags=re.MULTILINE)
    text = re.sub(r"^in vec2 qt_TexCoord0;.*\n", "", text, flags=re.MULTILINE)
    text = re.sub(r"^out vec4 fragColor;\n", "", text, flags=re.MULTILINE)

    # The stats texture becomes two numbers handed in from QML.
    text = text.replace(
        "vec2  st   = texelFetch(panelStats, ivec2(0), panelStatsLevel).rg;",
        "vec2  st   = panelStat;   // ported: no mipmap-reduce pass on the lock screen")

    # Qt composites with the item's opacity; the plugin draws direct.
    text = text.replace("fragColor = vec4(glassColor, 1.0) * aa;",
                        "fragColor = vec4(glassColor, 1.0) * aa * qt_Opacity;")
    text = text.replace("if (aa <= 0.0) { fragColor = vec4(0.0); return; }",
                        "if (aa <= 0.0) { fragColor = vec4(0.0); return; }")

    block = "\n".join(f"    {t:<5} {n};" for t, n in SCALARS)
    header = f"""#version 440

// GENERATED by splash/port-material.py from plugin/src/brolliglass.frag.
// Do not edit: edit the material and re-run.

layout(location = 0) in  vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {{
    mat4  qt_Matrix;
    float qt_Opacity;
{block}
}};

layout(binding = 1) uniform sampler2D source;
"""
    return header + text


def main():
    with open(SRC) as fh:
        ported = port(fh.read())
    with open(OUT_GLSL, "w") as fh:
        fh.write(ported)

    qsb = find_qsb()
    res = subprocess.run([qsb, "--glsl", "100es,120,150", "--hlsl", "50",
                          "--msl", "12", "-o", OUT_QSB, OUT_GLSL],
                         capture_output=True, text=True)
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr, file=sys.stderr)
        sys.exit(f"qsb failed on {OUT_GLSL}")
    print(f"{os.path.basename(SRC)} -> {os.path.basename(OUT_GLSL)} -> "
          f"{os.path.basename(OUT_QSB)} ({os.path.getsize(OUT_QSB)} bytes, "
          f"{len(SCALARS)} uniforms)")


if __name__ == "__main__":
    main()
